linters-settings:
  cyclop:
    skip-tests: true
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
    settings:
      rangeValCopy:
        sizeThreshold: 256
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: false
    require-specific: true
  varnamelen:
    ignore-decls:
      - w apiGateway.ResponseWriter

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - dupl
        - funlen
        - gocognit

linters:
  disable-all: true
  enable:
    - bodyclose
    - contextcheck
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gocognit
    - goconst
    - gocritic
    - godot
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ifshort
    - ineffassign
    - ireturn
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
      
run:
  issue-exit-code: 1
  timeout: 3m
  skip-dirs:
    - bin