name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  BE_Build_Deploy:
    name: BE Build Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      JWT_EXPIRE_MINS: ${{ secrets.JWT_EXPIRE_MINS }}
      SUCCESS_URL: ${{ secrets.SUCCESS_URL }}
      CANCEL_URL: ${{ secrets.CANCEL_URL }}
      COOKIE_DOMAIN: ${{ secrets.COOKIE_DOMAIN }}
      COOKIE_SECURE: ${{ secrets.COOKIE_SECURE }}
      CORS_ALLOWED_ORIGIN: ${{ secrets.CORS_ALLOWED_ORIGIN }}
      CR_PAT: ${{ secrets.CR_PAT }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull go images
        run: make docker_pull_be
      - name: Run Go tests
        run: make ci_tests_api
      - name: Build binary
        run: make ci_build_api
      - name: Deploy function
        run: make ci_deploy_api

  FE_Build_Deploy:
    name: FE Build Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_CF_DISTRIBUTION_ID: ${{ secrets.AWS_CF_DISTRIBUTION_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull js image
        run: make docker_pull_fe
      - name: Run JS tests
        run: make ci_tests_fe
      - name: Build FE
        run: make ci_build_fe
      - name: Deploy FE
        run: make ci_deploy_fe